### ISSUE TITLE
Error in Socket Connection

### ISSUE THREAD

**Issue by Andreiology** [lbbe-software/seqinr#13]
Hi! I am trying to use seqinr for my Bioinformatics Project and I did troubleshoot but still it gave me this message:

```
Error in socketConnection(host = host, port = port, server = server, blocking = blocking,  : 
  cannot open the connection
In addition: Warning message:
In socketConnection(host = host, port = port, server = server, blocking = blocking,  :
  pbil.univ-lyon1.fr:5558 cannot be opened
Error in choosebank("swissprot") : 
  I wasn't able to open the socket connection:
   o Check that your are connected to the internet.
   o Check that port 5558 is not closed by a firewall.
   o Try to increase timeout value (current is 5 seconds).
```

Thank you.

**Comment by simonpenel** [comment]
Dear Lawrence,

thanks for your e-mail and your interest in seqinr!
Sorry for the inconvenience with the database connection.
Unfortunately, we  had an unexpected power cut on the the whole campus and some servers are still down.
I will be away next week, but I report it to the rest of the team so they can restart the server, I think everything will be fine on Monday (tomorow)

All the best

Simon

**Comment by simonpenel** [comment]
The acnuc  server is working.

**Comment by simonpenel** [comment]
The acnuc server is working.
